apiVersion: v1
kind: ConfigMap
metadata:
  name: order-tracking-config
data:
  config.yml: |
    port: "8000"
    database:
      host: "postgres"
      port: "5432"
      username: "postgres"
      dbname: "postgres"
      sslmode: "disable"
      password: "qwerty"
    kafka:
      brokers: ["kafka:9092"]
      order_topic: "orders.events"
    redis:
      addr: "redis:6379"
      db: 0
      password: ""
    clickhouse:
      addr: "clickhouse:9000"
      database: "default"
    neo4j:
      uri: "neo4j://neo4j:7687"
      username: "neo4j"
      password: "password"
    telemetry:
      otlp_endpoint: "otel-collector:4317"

