FROM golang:1.25 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/order-consumer ./cmd/order-consumer

FROM gcr.io/distroless/base-debian12
WORKDIR /
COPY --from=build /out/order-consumer /order-consumer
USER 65532:65532
ENTRYPOINT ["/order-consumer"]
